name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: finki-hub/.github/.github/workflows/dependabot.yaml@d10f74eb5f2d9b377627dd390c4081c8b10867fc
    with:
      auto-merge-uv: false
